# Use this docker-compose file to host the site locally
version: '3.7'
services:
  nginx:
    build: docker/nginx-container
    image: milken/nginx-dev
    expose:
      - 80
      - 9222
    depends_on:
      - php
      - mysql
    links:
      - php
      - mysql
    volumes:
      - ".:/var/www"
    ports:
      - "8080:80"
      - "9222:9222"
    env_file:
      - .env

  php:
    build: docker/php-container
    image: milken/php-dev
    expose:
      - '9000'
      - '4444'
    external_links:
      - solr-ssl_solr-network:milkensolr-nginx
    volumes:
      - ".:/var/www"
      - type: bind
        source: $HOME/.ssh
        target: /root/.ssh
        read_only: true
    links:
      - grid
      - redis
    env_file:
      - .env

  mysql:
    build: docker/mysql-container
    image: milken/mysql-dev
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
    env_file:
      - .env

  redis:
    image: redis
    expose:
      - '6379'

  grid:
    image: mcr.microsoft.com/mssql/server:2017-CU8-ubuntu
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=drupal^99^DRUPAL
      - MSSQL_PID=developer
    expose:
      - '1433'
    ports:
      - "1433:1433"

volumes:
  web: {}
  db: {}
